#!/bin/bash
echo "##"
echo "# User Database"
echo "#"
echo "# Note that this file is consulted directly only when the system is running"
echo "# in single-user mode. At other times this information is provided by"
echo "# Open Directory."
echo "#"
echo "# See the opendirectoryd(8) man page for additional information about"
echo "# Open Directory."
echo "##"
cat /etc/passwd
